name: CI
#
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#workflow_dispatch:
#
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

#    runs-on: ubuntu-latest
    
    steps:
      - name: remote-bash
        uses: shinhwagk/remote-bash@0.0.1
        with:
          HOST: ${{secrets.HOST}}
          PORT: ${{secrets.PORT}}
          USERNAME: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          #target: ${{secrets.TARGET}}
          #source: "./scripts/*"
          args: ls /
 
   #   - uses: actions/checkout@v2
   #  - name: copy files to server
   #   - uses: appleboy/scp-action@master
   #     with:
   #       HOST: ${{secrets.HOST}}
   #       PORT: ${{secrets.PORT}}
   #       USERNAME: ${{secrets.USERNAME}}
   #       password: ${{secrets.PASSWORD}}
   #       target: ${{secrets.TARGET}}
   #       source: "./scripts/*"
   #       run: ls /opt/geonode/
          
      - name: Run a one-line script
        #run: ls /opt/geonode/

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
