name: CI
on:
  push:
    branches: [ main ]
#  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v2
      - name: remote-bash
        uses: shinhwagk/remote-bash@0.0.1
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
